### ISSUE TITLE
A complete example would be great.

### ISSUE THREAD

**Issue by mchambaud** [alexandrudima/typescript-with-globs#1]
Hey @alexandrudima 

I can't seem to get globs to work, I keep getting 

`env: node\r: No such file or directory`

tsconfig.json

{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitHelpers": false,
    "sourceMap": true,
    "noResolve": false
  },
  "files": [
    "typings/index.d.ts"
  ],
  "filesGlob": [
    "src/*_/_.ts"
  ],
  "exclude": [
    "node_modules",
    "typings",
    "test"
  ],
  "compileOnSave": true,
  "buildOnSave": false
}

**Comment by alexdima** [comment]
@mchambaud How did you install it? (via `npm install` or did you clone the repo?)

**Comment by mchambaud** [comment]
npm

**Comment by alexdima** [comment]
Archiving repo...
