### ISSUE TITLE
Don't think negation `!` (to exclude files/directories e.g. `!./**/*.spec.ts`) will work

### ISSUE THREAD

**Issue by basarat** [alexandrudima/typescript-with-globs#2]
From a quick code review of https://github.com/alexandrudima/typescript-with-globs/blob/master/lib/tscg.js#L62-L72

That said you can use blake embery's https://github.com/typestrong/tsconfig to get the desired filesGlob behavior that you can then expose as `tscg` :rose:

**Comment by alexdima** [comment]
Archiving repo...
